language: scala
scala:
  - 2.12.10
  - 2.11.12
jdk:
  - openjdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
